# Generated by Django 3.2.4 on 2023-11-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20231127_1400'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('team_a_score', models.PositiveIntegerField()),
                ('team_b_score', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.matchday')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teama', to='players.teams')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teamb', to='players.teams')),
            ],
            options={
                'unique_together': {('matchday', 'team_a', 'team_b')},
            },
        ),
    ]
