# Generated by Django 3.2.4 on 2023-12-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20231127_1400'),
        ('points', '0002_teamresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('matchplayed', models.BooleanField(default=True)),
                ('goal', models.PositiveIntegerField()),
                ('assist', models.PositiveIntegerField()),
                ('yellowcard', models.PositiveIntegerField()),
                ('redcard', models.PositiveIntegerField()),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.matchday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.player')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
