# Generated by Django 3.2.4 on 2023-12-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20231127_1400'),
        ('points', '0003_playerpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerpoints',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='playerpoints',
            unique_together={('player', 'matchday')},
        ),
    ]
