# Generated by Django 3.2.4 on 2023-11-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pics/', verbose_name='Team Picture'),
        ),
    ]
