# Generated by Django 3.2.4 on 2023-11-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_userselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='players',
        ),
        migrations.AddField(
            model_name='userselection',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='players.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userselection',
            name='player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='players.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userselection',
            name='player3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='players.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userselection',
            name='player4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='players.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userselection',
            name='player5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='players.player'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.UniqueConstraint(fields=('user', 'player1', 'player2', 'player3', 'player4', 'player5'), name='unique_user_selection'),
        ),
    ]
